print("system failure imminent!")
print("System reboot has been initiated")
print()
print("...rebooting sensory system")
print("...rebooting output motors")
print("...rebooting hover engine")
print()
print("System online")